version: '3.3'

services: 
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./volumes_data/mongo:/data/db
    env_file:
      - .env
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_OUT_PORT}:8081
    env_file:
      - .env
  server:
    build: 
      context: ./
      dockerfile: ./packages/server/Dockerfile 
    restart: always
    env_file:
      - .env
    
        